language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.5" 
  - "3.6"
  - "3.6" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "3.8-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev
before_install:
  - pip install --upgrade pytest
# command to install dependencies
install:
  - "pip install e ."
  - "pip install -r requirements_test.txt"
# command to run tests
script: py.test
